import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import pg from "pg";

const connectionString = process.env.BOARD_HYDRATION_POSTGRES_TEST_URL;

if (!connectionString) {
  console.log("ProjectV2 Board snapshot PostgreSQL test skipped: BOARD_HYDRATION_POSTGRES_TEST_URL is not set");
} else {
  const databaseUrl = new URL(connectionString);
  const loopbackHosts = new Set(["127.0.0.1", "[::1]", "localhost"]);
  assert.ok(loopbackHosts.has(databaseUrl.hostname), "Board hydration PostgreSQL test may only use loopback");
  assert.equal(databaseUrl.pathname, "/pilo_board_hydration_test");

  const { Client } = pg;
  const client = new Client({ connectionString });
  let connected = false;

  try {
    await client.connect();
    connected = true;
    assert.equal((await client.query("SELECT current_database() AS name")).rows[0].name, "pilo_board_hydration_test");
    await client.query("DROP SCHEMA public CASCADE; CREATE SCHEMA public");
    await client.query(`
      CREATE TYPE github_sync_status AS ENUM ('queued', 'running', 'success', 'failed');
      CREATE TABLE github_projects_v2 (
        id UUID PRIMARY KEY,
        workspace_id UUID NOT NULL,
        title TEXT NOT NULL
      );
      CREATE TABLE github_repositories (
        id UUID PRIMARY KEY,
        workspace_id UUID NOT NULL
      );
      CREATE TABLE github_project_v2_repositories (
        project_v2_id UUID NOT NULL,
        repository_id UUID NOT NULL
      );
      CREATE TABLE github_project_v2_fields (
        id UUID PRIMARY KEY,
        project_v2_id UUID NOT NULL,
        is_status_field BOOLEAN NOT NULL
      );
      CREATE TABLE github_project_v2_field_options (
        id UUID PRIMARY KEY,
        field_id UUID NOT NULL REFERENCES github_project_v2_fields(id) ON DELETE CASCADE,
        github_option_id TEXT NOT NULL,
        option_name TEXT NOT NULL,
        normalized_name TEXT NOT NULL,
        color TEXT,
        position INTEGER
      );
      CREATE TABLE boards (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        workspace_id UUID NOT NULL,
        repository_id UUID NOT NULL,
        project_v2_id UUID NOT NULL,
        status_field_id UUID,
        last_sync_status github_sync_status,
        last_synced_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE(project_v2_id, repository_id)
      );
      CREATE TABLE board_columns (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        board_id BIGINT NOT NULL REFERENCES boards(id) ON DELETE CASCADE,
        status_option_id UUID REFERENCES github_project_v2_field_options(id) ON DELETE SET NULL,
        status_option_github_id TEXT,
        normalized_name TEXT,
        name TEXT NOT NULL,
        position INTEGER NOT NULL DEFAULT 0,
        color TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE(board_id, position),
        UNIQUE(board_id, status_option_id)
      );
      CREATE TABLE github_issues (
        id UUID PRIMARY KEY,
        workspace_id UUID NOT NULL,
        repository_id UUID NOT NULL,
        github_node_id TEXT,
        issue_number BIGINT NOT NULL,
        title TEXT NOT NULL,
        body TEXT,
        html_url TEXT,
        state TEXT,
        labels JSONB,
        assignees JSONB,
        milestone JSONB,
        github_updated_at TIMESTAMPTZ,
        raw JSONB
      );
      CREATE TABLE github_project_v2_items (
        id UUID PRIMARY KEY,
        project_v2_id UUID NOT NULL,
        workspace_id UUID NOT NULL,
        issue_id UUID NOT NULL,
        content_type TEXT NOT NULL,
        is_archived BOOLEAN NOT NULL DEFAULT false,
        status_option_id UUID,
        status_option_github_id TEXT,
        status_normalized_name TEXT,
        github_project_item_node_id TEXT,
        position DOUBLE PRECISION
      );
      CREATE TABLE pilo_issues (
        id BIGSERIAL PRIMARY KEY,
        board_id BIGINT NOT NULL,
        column_id BIGINT NOT NULL,
        workspace_id UUID NOT NULL,
        repository_id UUID NOT NULL,
        github_issue_id UUID NOT NULL,
        project_item_id UUID NOT NULL,
        github_issue_node_id TEXT,
        github_project_item_node_id TEXT,
        github_issue_number BIGINT NOT NULL,
        issue_number TEXT NOT NULL,
        title TEXT NOT NULL,
        body TEXT,
        html_url TEXT,
        state TEXT,
        labels JSONB,
        assignees JSONB,
        milestone JSONB,
        position BIGINT NOT NULL,
        github_updated_at TIMESTAMPTZ,
        last_synced_at TIMESTAMPTZ,
        raw JSONB,
        updated_at TIMESTAMPTZ DEFAULT now(),
        UNIQUE(column_id, position),
        UNIQUE(board_id, issue_number)
      );
    `);
    await client.query(await readFile(new URL("../../../../db/migrations/106_fix_pilo_issue_hydration_position_offset.sql", import.meta.url), "utf8"));
    await client.query(await readFile(new URL("../../../../db/migrations/108_reconcile_project_v2_field_board_snapshots.sql", import.meta.url), "utf8"));

    const workspaceId = "11111111-1111-4111-8111-111111111111";
    const repositoryId = "22222222-2222-4222-8222-222222222222";
    const projectId = "33333333-3333-4333-8333-333333333333";
    const fieldId = "44444444-4444-4444-8444-444444444444";
    const todoOptionId = "55555555-5555-4555-8555-555555555555";
    const doingOptionId = "66666666-6666-4666-8666-666666666666";
    const removedOptionId = "77777777-7777-4777-8777-777777777777";
    const todoIssueId = "88888888-8888-4888-8888-888888888888";
    const removedIssueId = "99999999-9999-4999-8999-999999999999";
    const todoItemId = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
    const removedItemId = "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb";

    await client.query(
      `
        INSERT INTO github_projects_v2 VALUES ($1, $2, 'PILO MVP');
        INSERT INTO github_repositories VALUES ($3, $2);
        INSERT INTO github_project_v2_repositories VALUES ($1, $3);
        INSERT INTO github_project_v2_fields VALUES ($4, $1, true);
        INSERT INTO github_project_v2_field_options(id, field_id, github_option_id, option_name, normalized_name, color, position) VALUES
          ($5, $4, 'todo', 'Todo', 'todo', 'BLUE', 2),
          ($6, $4, 'doing', 'Doing', 'doing', 'YELLOW', 1),
          ($7, $4, 'removed', 'Removed', 'removed', 'RED', 3);
        INSERT INTO boards(id, name, workspace_id, repository_id, project_v2_id, status_field_id, last_sync_status)
        VALUES (10, 'Old name', $2, $3, $1, $4, 'success');
        INSERT INTO board_columns(id, board_id, status_option_id, status_option_github_id, normalized_name, name, position, color) VALUES
          (101, 10, $5, 'todo', 'todo', 'Todo old', 1, 'GRAY'),
          (102, 10, $6, 'doing', 'doing', 'Doing old', 2, 'GRAY'),
          (103, 10, $7, 'removed', 'removed', 'Removed', 3, 'RED'),
          (104, 10, NULL, NULL, 'unmapped', 'Unmapped', 4, '#8a93a6'),
          (105, 10, NULL, NULL, 'unmapped', 'Unmapped copy', 5, '#8a93a6');
        DELETE FROM github_project_v2_field_options WHERE id = $7;
        INSERT INTO github_issues(id, workspace_id, repository_id, github_node_id, issue_number, title, body, html_url, state, labels, assignees, milestone, github_updated_at, raw) VALUES
          ($8, $2, $3, 'I_todo', 1, 'Todo issue', NULL, 'https://example.test/1', 'open', '[]', '[]', 'null', now(), '{}'),
          ($9, $2, $3, 'I_removed', 2, 'Removed issue', NULL, 'https://example.test/2', 'open', '[]', '[]', 'null', now(), '{}');
        INSERT INTO github_project_v2_items(id, project_v2_id, workspace_id, issue_id, content_type, is_archived, status_option_id, status_option_github_id, status_normalized_name, github_project_item_node_id, position) VALUES
          ($10, $1, $2, $8, 'ISSUE', false, $5, 'todo', 'todo', 'PVTI_todo', 2),
          ($11, $1, $2, $9, 'ISSUE', false, NULL, 'removed', 'removed', 'PVTI_removed', 1);
      `,
      [projectId, workspaceId, repositoryId, fieldId, todoOptionId, doingOptionId, removedOptionId, todoIssueId, removedIssueId, todoItemId, removedItemId]
    );

    const hydrated = await client.query("SELECT hydrate_pilo_board_from_github($1::uuid, $2::uuid)::text AS board_id", [projectId, repositoryId]);
    assert.equal(hydrated.rows[0].board_id, "10");

    const columns = await client.query("SELECT id::text, name, status_option_github_id, normalized_name, position FROM board_columns WHERE board_id = 10 ORDER BY position ASC");
    assert.deepEqual(columns.rows.map(({ id, ...column }) => column), [
      { name: "Doing", status_option_github_id: "doing", normalized_name: "doing", position: 1 },
      { name: "Todo", status_option_github_id: "todo", normalized_name: "todo", position: 2 },
      { name: "Unmapped", status_option_github_id: null, normalized_name: "unmapped", position: 3 }
    ]);
    const issues = await client.query("SELECT title, column_id::text FROM pilo_issues ORDER BY title ASC");
    assert.deepEqual(issues.rows, [
      { title: "Removed issue", column_id: columns.rows[2].id },
      { title: "Todo issue", column_id: columns.rows[1].id }
    ]);
  } finally {
    if (connected) {
      await client.query("DROP SCHEMA public CASCADE; CREATE SCHEMA public");
    }
    await client.end();
  }
}
